# Generated by Django 5.0.6 on 2024-10-01 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iils', '0005_answer_voter_question_voter_alter_answer_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('pcode', models.CharField(max_length=10)),
                ('pname', models.TextField()),
                ('unitprice', models.IntegerField(default=0)),
                ('discountrate', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('mainfunc', models.CharField(default='', max_length=100)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('detailfunc', models.CharField(default='', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
