"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import os
import requests
#import pandas as pd
#from aspose.cells import Workbook

url = 'http://apis.data.go.kr/1220000/nitemtrade/getNitemtradeList?strtYymm=202302&endYymm=202401&hsSgn=1001999090&cntyCd=US&serviceKey=diUBgK2%2Bo8yKd9Ki8Fl2h6GNrzg%2B0guxZ0TDHh%2FhZs0xwT6wg4iDIhSRw9Yy6z%2FBqzX76zT%2FmycLL9P6gSNppQ%3D%3D'
params ={'serviceKey' : '서비스키', 'strtYymm' : '202302', 'endYymm' : '202401', 'hsSgn' : '1001999090', 'cntyCd' : 'US' }

response = requests.get(url, params=params)
status = response.status_code

print(response.content)


#filename = '엑셀파일 이름 넣기'

#df_excel = pd.read_excel(filename)

#print(df_excel)
# 엑셀에 있는 데이터들이 출력

#pd.read_excel(filename,
#                  sheet_name = '서울',
#                  header = None,
#                  names = ['일시','평균','최저','최고'],
#                  index_col = None,
#                  usecols = "C:F",
#                  dtype = {'일시':str, '평균':float, '최저':float, '최고':float},
#                  skiprows = 32,
#                  nrows = 28,
#                  na_values = 'nan',
#                  thousands = ',')

#df = pd.DataFrame([[11, 21, 31], [12, 22, 32], [31, 32, 33]],
 #                 index=['one', 'two', 'three'], columns=['a', 'b', 'c'])

#print(df)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-coyk75sd)xql1)=1b+c$(-)8vogcyc48@ldi!d(n-2_y+qqhv!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['52.79.143.4']


# Application definition

INSTALLED_APPS = [
    'common.apps.CommonConfig',
    'iils.apps.IilsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 로그인 성공후 이동하는 URL
LOGIN_REDIRECT_URL = '/'
